apiVersion: v1
kind: Service
metadata:
  labels:
    app: conf
    tier: backend
    run: conf
    visualize: "true"
  name: conf
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: conf
    tier: backend
