apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: config-service
    visualize: "true"
  name: config-service
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: config-service
        tier: backend
        track: stable
        run: config-service
        visualize: "true"
    spec:
      containers:
      - image: lassehavenielsen/config-server-rpi:latest
        name: config-service
