apiVersion: v1
kind: Service
metadata:
  labels:
    app: orders
    tier: backend
    run: orders
    visualize: "true"
  name: orders
spec:
  clusterIP: 10.0.0.213
  ports:
  - port: 9003
    protocol: TCP
    targetPort: 9003
  selector:
    app: orders
    tier: backend
