apiVersion: v1
kind: Service
metadata:
  labels:
    app: products
    tier: backend
    run: products
    visualize: "true"
  name: products
spec:
  clusterIP: 10.0.0.211
  ports:
  - port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: products
    tier: backend
