apiVersion: v1
kind: Service
metadata:
  labels:
    app: ui
    tier: frontend
    run: ui
    visualize: "true"
  name: ui
spec:
  externalIPs:
  - 192.168.1.51
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    app: ui
    tier: frontend
