apiVersion: v1
kind: Deployment
metadata:
  labels:
    run: users
    visualize: "true"
  name: users
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: users
        tier: backend
        track: stable
        run: users
        visualize: "true"
    spec:
      containers:
      - image: lassehavenielsen/users:latest
        name: users
