apiVersion: v1
kind: Service
metadata:
  labels:
    app: users
    tier: backend
    run: users
    visualize: "true"
  name: users
spec:
  clusterIP: 10.0.0.212
  ports:
  - port: 9002
    protocol: TCP
    targetPort: 9002
  selector:
    app: users
    tier: backend
